Add tests for CCTRI-1579
CiscoSecurity/tr-05-api-module pull request #85
Opened 2020-09-24 09:02 UTC by mistergreen22

2020-09-29 10:27 UTC, GeorgiyII commented on tests/functional/tests/test_ctr_05_api.py
> +        pass
you will have the green build if you have a HTTPError.
I think that we need to know if HTTPError will be here

2020-09-29 10:28 UTC, GeorgiyII commented on tests/functional/tests/test_ctr_05_api.py
> +        pass
like in previous comment

2020-09-29 10:43 UTC, mistergreen22 commented on tests/functional/tests/test_ctr_05_api.py
> +        pass
hmm, the HTTPError raises exactly here because we use expired (and invalid random in second test) token. You see, we check that if we use expired token we won't have valid output (else assertion wouldn't pass), moreover the HTTPError error raises always, if we didn't catch it fail our tests. I don't know the other way to check this, if you better answer please let me know.

2020-09-29 10:43 UTC, mistergreen22 commented on tests/functional/tests/test_ctr_05_api.py
> +        pass
answered in previous comment

2020-09-29 11:01 UTC, mistergreen22 commented on tests/functional/tests/test_ctr_05_api.py
> +        pass
![image](https://user-images.githubusercontent.com/44807224/94550380-4bfc3a00-025c-11eb-902e-1b4193666cfb.png)

2020-09-29 12:18 UTC, GeorgiyII commented on tests/functional/tests/test_ctr_05_api.py
> +        pass
ok, so why you need this try-except here?)

2020-09-29 12:19 UTC, GeorgiyII approved these changes

2020-09-29 12:23 UTC, GeorgiyII requested changes
You can use pytest functionality for checking errors that raised

```
with pytest.raises(HTTPError):
       assert not module_tool_client_token.inspect.inspect(..)
```

2020-09-29 12:28 UTC, GeorgiyII reviewed
```
assert not module_tool_client_token.inspect.inspect(
            {'content': '1.1.1.1'}) == [
                       {'type': 'ip', 'value': '1.1.1.1'}
        ]
```
i think that there will be better:
```
assert module_tool_client_token.inspect.inspect(
            {'content': '1.1.1.1'}) != [
                       {'type': 'ip', 'value': '1.1.1.1'}
        ]
```

2020-09-29 12:39 UTC, GeorgiyII commented on tests/functional/tests/test_ctr_05_api.py
> +def test_python_module_negative_token(module_tool_client_token, token):
why you transfer `module_tool_client_token` and not use that, i think that you can write `module_tool_client_token` like function and use that with different tokens, because in fixtures it has very narrow using

2020-09-29 12:40 UTC, GeorgiyII commented on tests/functional/tests/test_ctr_05_api.py
> +def test_python_module_negative_token(module_tool_client_token, token):
and in previous test too

2020-09-30 06:50 UTC, mmysk commented on tests/functional/tests/conftest.py
> +    return {'Authorization': 'Bearer {}'.format(module_token)}
There is cleaner way to interpolate strings using f-strings:
```suggestion
    return {'Authorization': f'Bearer {module_token}'
```

2020-09-30 06:54 UTC, nonspher commented on tests/functional/tests/test_ctr_05_api.py
> +    time.sleep(601)
I'm not sure that good idea used the 'time.sleep()'. Gosha proposed a solution to receive two tokens.

2020-09-30 09:02 UTC, mistergreen22 commented on tests/functional/tests/conftest.py
> +    return {'Authorization': 'Bearer {}'.format(module_token)}
Hi, it was done to make code compatible with different versions on python, we provide support  up to python 2.7 for this particular library(you can see  it in travis file).

2020-09-30 09:27 UTC, mistergreen22 commented
> You can use pytest functionality for checking errors that raised
> 
> ```
> with pytest.raises(HTTPError):
>        assert not module_tool_client_token.inspect.inspect(..)
> ```

yup thats good idea!

2020-09-30 09:27 UTC, mistergreen22 commented
> ```
> assert not module_tool_client_token.inspect.inspect(
>             {'content': '1.1.1.1'}) == [
>                        {'type': 'ip', 'value': '1.1.1.1'}
>         ]
> ```
> 
> i think that there will be better:
> 
> ```
> assert module_tool_client_token.inspect.inspect(
>             {'content': '1.1.1.1'}) != [
>                        {'type': 'ip', 'value': '1.1.1.1'}
>         ]
> ```

ok

2020-09-30 09:41 UTC, mistergreen22 commented on tests/functional/tests/test_ctr_05_api.py
> +def test_python_module_negative_token(module_tool_client_token, token):
yup in this case i just forgot to remove this fixture, but overall I think fixtures is pretty useful pytest functional and it suits us well(and we always can change the scope to function if we need), plus sometimes some weird things happening with imports in this lib, to avoid it i prefer to use fixtures instead of functions.

2020-09-30 09:44 UTC, mistergreen22 commented on tests/functional/tests/test_ctr_05_api.py
> +    time.sleep(601)
In our case it doesn't work, because generation new token doesn't expiring the old one

2020-09-30 11:10 UTC, GeorgiyII approved these changes

2020-09-30 14:06 UTC, mmysk approved these changes

2020-09-30 14:29 UTC, nonspher approved these changes

2020-09-30 14:53 UTC, merged